search: 
  enable: true
  service: hexo

links:
  - name: My github
    url: https://github.com/PngWnA

menu:
  - name: Home
    slug: home
    url: /
  - name: About
    slug: about
    url: /about
  - name: Archives
    slug: archives
    url: /archives

widgets:
  - about
  - categories

less:
  compress: true

social:
- slug: github
  url: https://github.com/PngWnA
- slug: rss
	url: /atom.xml
